; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30140.0 

	TITLE	D:\cprog\first.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_i$ = -4						; size = 4
_main	PROC
; File D:\cprog\first.cpp
; Line 2
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 4
	mov	DWORD PTR _i$[ebp], 0
; Line 5
	mov	eax, DWORD PTR _i$[ebp]
; Line 6
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
